### ISSUE TITLE
java-jdbc.sql/update name cashes with clojure.core/update

### ISSUE THREAD

**Issue by Kungi** [seancorfield/jsql#4]
I see the following warning when using java-jdbc.sql with clojure 1.7.0-RC1.
`WARNING: update already refers to: #'clojure.core/update in namespace: java-jdbc.sql, being replaced by: #'java-jdbc.sql/update`
Can you please add

    (:refer-clojure :exclude [update])
to your `ns` form.

**Comment by seancorfield** [comment]
Thank you! Good catch! I'm no longer actively using this library so I hadn't noticed that issue.

**Comment by Kungi** [comment]
Did you release this change on clojars?

**Comment by seancorfield** [comment]
Haven't had a chance yet. Will do it today with any updated version etc.

**Comment by seancorfield** [comment]
Released/promoted: https://clojars.org/java-jdbc/dsl/versions/0.1.3

**Comment by Kungi** [comment]
Thank you very much.
